# Generated by Django 5.0 on 2023-12-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_destination_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='http_method',
            field=models.CharField(max_length=20),
        ),
    ]
