# Generated by Django 5.0 on 2023-12-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_destination_http_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='url',
        ),
    ]
