# Generated by Django 5.0 on 2023-12-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_destination_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
